### ISSUE TITLE
Minor confusion and typo in HTTP chapter

### ISSUE THREAD

**Issue by ozym4nd145** [captn3m0/the-joy-of-software-development#3]
# In chapter - "HTTP, REST and APIs"

_Confusing statement-_
"Opens a TCP socket to josd.captnemo.in" should be changed to "Opens a TCP socket to the website" as it was mentioned before that "When you are making a web request to **any server**, your browser does the following: ".

_Typo ->_
"The body on the **oter** hand is the content of the request"

**Comment by captn3m0** [comment]
Thanks, will fix.
